version: '3.9'

services:

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    ports:
      - "5432:5432"
    volumes:
      - /db/data:/var/lib/postgresql/data

volumes:
  data: